### ISSUE TITLE
Error: is not a Graph or Graph factory function

### ISSUE THREAD

**Issue by henryf3** [langchain-ai/langgraph-studio#100]
Hi buddies, I am using an abstraction for my project, so my variable graph has class `core.workflow.agent_workflow.AgentWorkflow ` instead of `langgraph.graph.state.CompiledStateGraph`.  Did you implement a type checking function?

It was working one week ago, in which library did you make that change (langchain, langraph?), or in langraph studio itself?. How can i set the libraries version used in langraph studio?

![image](https://github.com/user-attachments/assets/32758885-21d7-46fb-9ba4-de3cedb4afeb)

**Comment by dqbd** [comment]
Hello, the check comes from the underlying LangGraph runtime and the check essentially boils down to.

```python
from langgraph.graph import Graph
from langgraph.pregel import Pregel
if not isinstance(graph, Graph) and not isinstance(graph, Pregel):
   raise ValueError("...")
```

Could you share a reproducible example?
