### ISSUE TITLE
Using async/await with langgraphJS

### ISSUE THREAD

**Issue by gpiroux** [langchain-ai/langgraph-studio#102]
It seems not possible to use async/await with langgraphJS on langgraph studio ?
Is it a current limitation or a wrong configuration ?
I used the langgraph-studio-starter to bootstrap the project.

**Comment by hinthornw** [comment]
Do you have any example code to share? All our defaults and code examples are async in LangGraph JS & python, so some sample code would help us be more of assistance.

**Comment by gpiroux** [comment]
I had clear message yesterday telling that the async/await paterne was forbidden in cjs but after multiple retry today that finally worked... Thank you any way.
