### ISSUE TITLE
ValueError: License key is not valid - Issues while following the YouTube tutorial

### ISSUE THREAD

**Issue by serafinski** [langchain-ai/langgraph-studio#11]
Hi guys,
while trying to follow tutorial [https://www.youtube.com/watch?v=pLPJoFvq4_M](url) I'm encountering the following error:
![CleanShot 2024-08-01 at 23 58 37@2x](https://github.com/user-attachments/assets/700ce8d7-6638-4cbd-8262-13286df1479e)

I found the following issues:
[https://github.com/langchain-ai/chat-langchain/issues/339](url)
[https://github.com/langchain-ai/langgraph/issues/893](url)

but am not able to fix it 🫤.

Please advise what can be done to get up and running! 😄 

Thanks and sorry for the hassle!

**Comment by serafinski** [comment]
Base on what I can see in the logs, it seems like there is an issue with a key:
```json
langgraph-api-1       | 2024-08-01 21:55:04,704:WARNING:langgraph_license.validation No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment.
langgraph-api-1       | 2024-08-01 21:55:05,011:INFO:httpx HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 403 Forbidden"
langgraph-api-1       | 2024-08-01 21:55:05,012:ERROR:uvicorn.error Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 730, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 18, in lifespan
langgraph-api-1       | ValueError: License key is not valid
langgraph-api-1       | 
langgraph-api-1       | 2024-08-01 21:55:05,012:ERROR:uvicorn.error Application startup failed. Exiting.
```

I have LANGSMITH_API_KEY="lsv2_pt_**************************" specified in .env file. Do I need to have a different license than a Personal one?

**Comment by nfcampos** [comment]
Hi @serafinski the desktop app should generate a langsmith api key for auth purposes, so you don't need to have it in your env file. Does it work if you remove it?

**Comment by serafinski** [comment]
Hi @nfcampos, 
I can confirm that removing all the LANGSMITH_API_KEY seem to fix the issue 😄! 

_Maybe README should be updated so it explicitly says to not include it 😛_

Thanks for the quick response!
