### ISSUE TITLE
Cannot use local models (ChatOllama)

### ISSUE THREAD

**Issue by robbiemu** [langchain-ai/langgraph-studio#112]
I am using the studio in module 2 of the Intro to LangGraph from Langchain Academy. (The same issue occurs with all models relying on a model if that model is set to ChatOllama):

I've modified requirements.txt to remove langchain-openai and add langchain-ollama:
```
langgraph
langchain-core
langchain-community
langchain-ollama
```

I'm aware of no changes needed in the langraph.json:
```json
{
  "dockerfile_lines": [],
  "graphs": {
    "chatbot": "./chatbot.py:graph"
  },
  "env": "./.env",
  "python_version": "3.11",
  "dependencies": [
    "."
  ]
}
```

in the graph I've swapped in my local model instead of openai:
```py
# We will use this model for both the conversation and the summarization
#from langchain_openai import ChatOpenAI
#model = ChatOpenAI(model="gpt-4o", temperature=0) 
from langchain_ollama import ChatOllama

model = ChatOllama(
    model = "mistral-nemo:12b-instruct-2407-q8_0",
    temperature = 0.8,
    num_ctx=8192,
    num_predict = 4096,
)
```

This studio is a reproduction of the coursework in the Jupyter notebook, and there, I receive no issues. In the studio, however, when I submit a message, I get

"Connect Error: [Errno 111] Connection refused"

# Expected:
If opening this port for the chain in docker is configurable in the json file, it should be required even for OpenAI models -- otherwise you are tightly coupling the studio to OpenAI.
The outbound ports should either always be explicit, or every chat* model in langchain should have its default port open.

note: see also the original issue I opened at the GitHub for [langchain academy](https://github.com/langchain-ai/langchain-academy/issues/13)

**Comment by hwchase17** [comment]
i think this is possible we just need instructions on how to do it

**Comment by robbiemu** [comment]
I think this is done something like:

dockerfile:
```dockerfile
EXPOSE <OLLAMA_PORT> 
```
then where you run the docker file:
```bash
docker run -d -p <HOST_PORT>:<OLLAMA_PORT> <your_image_name>
```
The default port needed is 11434

**Comment by robbiemu** [comment]
I'm not an expert but... The Ollama port it is trying to contact is 11434. This is how you could expose that port, I believe: `docker run -d -p 11434:11434 <langgraph_studio_image>` 

The -p flag has no equivalent inside of the Dockerfiile. You *can* do the same port forwarding if it was a docker compose instead, using the "Ports" section.

I have no idea how to add configuration options to the langgraph.json (for decoupling), but I'd be happy to help if I could :)

**Comment by timbogit** [comment]
I ran into the same problem / had the same use case. Thanks so much for figuring this out, @robbiemu ! 🥳 

Using the `base_url="http://host.docker.internal:11434"` for local Ollama models might be worth adding to an FAQ / README section.
Thoughts, @hwchase17? 🙇

**Comment by deanchanter** [comment]
`base_url="http://host.docker.internal:11434"` did not work for me.  This only difference is that I am using Orbstack. Could that be the issue?

**Comment by PlebeiusGaragicus** [comment]
Same problem.  Also `base_url="http://host.docker.internal:11434"` did not resolve this.

**Comment by dqbd** [comment]
Updated in README.md!
