### ISSUE TITLE
Configurable button not showing

### ISSUE THREAD

**Issue by betimd** [langchain-ai/langgraph-studio#117]
Hey there,

I updated LangGraph Studio and I miss Configurable button (as shown in screenshot below). 

Is there a bug or you intentionally not showing it anymore. 

Note: Haven't change config_schema since last working version, and nothing complex just model_name as in official sample.

Screenshot:
<img width="481" alt="image" src="https://github.com/user-attachments/assets/42bb57e0-00e2-4ac7-8b6e-8d85c3dc4e0d">

**Comment by dqbd** [comment]
Hello @betimd! Could you try updating LangGraph in your project to latest version?

**Comment by betimd** [comment]
Yes it worked. After update, surprisingly enough I had to restart computer to make it work. Maybe bc of any cache or docker related stuff.
