### ISSUE TITLE
Authentication Not Working on Mac Sonoma M2 Chip (LangGraph 0.0.21)

### ISSUE THREAD

**Issue by atulmkamble** [langchain-ai/langgraph-studio#118]
System Details:
- MacOS: Sonoma 14.6.1
- Macbook Pro: M2 Chip
- LangGraph Studio Version: 0.0.21 (0.0.21)

Steps to reproduce:
1. Move the app in the Application folder
2. Open LangGraph Studio on Mac
3. Click the Login to LangSmith button and authenticate at the LangSmith website (US region)
4. The authentication succeeds but nothing changes on the Mac app (Attached snapshot 1).
![1](https://github.com/user-attachments/assets/389dc284-5af0-49f7-bb8c-37bfa93c5137)
5. Copying the authentication token on the website and pasting it into the app does not work either (Attached snapshot 2).
![2](https://github.com/user-attachments/assets/773e3136-ab7e-47bc-98a7-0aad7c1465f3)

This issue is similar to https://github.com/langchain-ai/langgraph-studio/issues/39

**Comment by dqbd** [comment]
Hello! We've published a new 0.0.22 version, which should hopefully solve the authentication issues!

**Comment by atulmkamble** [comment]
Hello @dqbd, I was not using any proxy. However, I have downloaded 0.0.22 and confirm that the authentication is working now. Thank You!
