### ISSUE TITLE
Start up hangs on "POST /assistants/search 200"

### ISSUE THREAD

**Issue by shoomonperry** [langchain-ai/langgraph-studio#119]
Hi I'm trying to use the latest version of langgraph-studio (v0.0.21) with a moderately complicated application we've built in langgraph.  It seems to hang and repeat "POST /assistants/search 200".  Complete logs below.

What am I doing wrong?...

----------

> Running "docker pull langchain/langgraph-api:3.11"
> Running "docker image prune -f --filter label=com.docker.compose.project=langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469"
> Running "docker image prune -f --filter label=com.docker.compose.project=langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469"
> Running "docker compose --project-directory /Users/shoomonperry/code/Langserve-jay --project-name langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469 -f - up --remove-orphans --watch"
> 3.11: Pulling from langchain/langgraph-api
> Digest: sha256:3eaf5fd29845e57481ab17083045021296bf11fed0fa7aecc229bf6efd7f16e2
> Status: Image is up to date for langchain/langgraph-api:3.11
> docker.io/langchain/langgraph-api:3.11
> Total reclaimed space: 0B
> Total reclaimed space: 0B
> #0 building with "desktop-linux" instance using docker driver
> 
> #1 [langgraph-api internal] load build definition from Dockerfile
> #1 transferring dockerfile: 723B 0.0s done
> #1 WARN: JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 13)
> #1 DONE 0.0s
> 
> #2 [langgraph-api internal] load metadata for docker.io/langchain/langgraph-api:3.11
> #2 DONE 0.0s
> 
> #3 [langgraph-api internal] load .dockerignore
> #3 transferring context: 2B done
> #3 DONE 0.0s
> 
> #4 [langgraph-api stage-0 1/4] FROM docker.io/langchain/langgraph-api:3.11
> #4 DONE 0.0s
> 
> #5 [langgraph-api internal] load build context
> #5 transferring context: 14.89kB 0.0s done
> #5 DONE 0.0s
> 
> #6 [langgraph-api stage-0 2/4] ADD ./src /deps/__outer_src/src
> #6 CACHED
> 
> #7 [langgraph-api stage-0 3/4] RUN set -ex &&     for line in '[project]'                 'name = "src"'                 'version = "0.1"'                 '[tool.setuptools.package-data]'                 '"*" = ["**/*"]'; do         echo "$line" >> /deps/__outer_src/pyproject.toml;     done
> #7 CACHED
> 
> #8 [langgraph-api stage-0 4/4] RUN --mount=type=cache,target=/root/.cache/pip PYTHONDONTWRITEBYTECODE=1 pip install -c /api/constraints.txt -e /deps/*
> #8 CACHED
> 
> #9 [langgraph-api] exporting to image
> #9 exporting layers done
> #9 writing image sha256:435c6af894ab6ea9c10f812679e2a2120bcbcbde688e6c57f6310a505ddd751b done
> #9 naming to docker.io/library/langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469-langgraph-api done
> #9 DONE 0.0s
>  Network langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469_default  Creating
>  Network langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469_default  Created
>  Container langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469-langgraph-postgres-1  Creating
>  Container langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469-langgraph-redis-1  Creating
>  Container langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469-langgraph-redis-1  Created
>  Container langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469-langgraph-postgres-1  Created
>  Container langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469-langgraph-api-1  Creating
>  Container langserve-jay-87548cfad804f070fa35fe5c0f442c984b97259dcca279808c3f35c1bf2db469-langgraph-api-1  Created
>         ⦿ Watch enabled
> Attaching to langgraph-api-1, langgraph-postgres-1, langgraph-redis-1
> langgraph-redis-1     | 1:C 17 Sep 2024 16:54:03.142 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> langgraph-redis-1     | 1:C 17 Sep 2024 16:54:03.143 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
> langgraph-redis-1     | 1:C 17 Sep 2024 16:54:03.143 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
> langgraph-redis-1     | 1:M 17 Sep 2024 16:54:03.143 * monotonic clock: POSIX clock_gettime
> langgraph-redis-1     | 1:M 17 Sep 2024 16:54:03.144 * Running mode=standalone, port=6379.
> langgraph-redis-1     | 1:M 17 Sep 2024 16:54:03.144 # Server initialized
> langgraph-redis-1     | 1:M 17 Sep 2024 16:54:03.146 * Ready to accept connections
> langgraph-postgres-1  | 
> langgraph-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
> langgraph-postgres-1  | 
> langgraph-postgres-1  | 2024-09-17 16:54:03.176 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
> langgraph-postgres-1  | 2024-09-17 16:54:03.176 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> langgraph-postgres-1  | 2024-09-17 16:54:03.176 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> langgraph-postgres-1  | 2024-09-17 16:54:03.177 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> langgraph-postgres-1  | 2024-09-17 16:54:03.181 UTC [29] LOG:  database system was shut down at 2024-09-17 16:52:51 UTC
> langgraph-postgres-1  | 2024-09-17 16:54:03.189 UTC [1] LOG:  database system is ready to accept connections
> langgraph-api-1       | info | Will watch for changes in these directories: ['/deps/__outer_src/src']
> langgraph-api-1       | info | Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
> langgraph-api-1       | info | Started reloader process [1] using StatReload
> langgraph-api-1       | info | Started server process [8]
> langgraph-api-1       | info | Waiting for application startup.
> langgraph-api-1       | warning | No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment.
> langgraph-api-1       | info | HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK"
> langgraph-api-1       | info | Starting 10 background workers
> langgraph-api-1       | info | Application startup complete.
> langgraph-api-1       | info | POST /assistants/search 200 2ms
> langgraph-api-1       | info | POST /assistants/search 200 9ms
> langgraph-api-1       | info | POST /assistants/search 200 4ms
> langgraph-api-1       | info | POST /assistants/search 200 5ms
> langgraph-api-1       | info | POST /assistants/search 200 10ms
> langgraph-api-1       | info | POST /assistants/search 200 6ms
> langgraph-api-1       | info | POST /assistants/search 200 15ms
> langgraph-api-1       | info | POST /assistants/search 200 14ms

**Comment by dqbd** [comment]
Hello @shoomonperry! Would it be possible to share the contents of `langgraph.json`? Seems like no graphs are being loaded by the API server?
