### ISSUE TITLE
Is it possible to use Rancher desktop in the near future ?

### ISSUE THREAD

**Issue by dubreuil534** [langchain-ai/langgraph-studio#122]
"Hello, I am asking the question because my company uses Rancher instead of Docker Desktop for licensing reasons. Is it in your plans to support this, as it currently does not work?"

**Comment by stephenl03** [comment]
Rancher Desktop works, you might just need to make some slight adjustments to your environment. Check out this closed issue https://github.com/langchain-ai/langgraph-studio/issues/24

**Comment by olafgeibig** [comment]
It seems to be enough to symlink the docker binary:
```sudo ln -sf "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker" /usr/local/bin/docker```

**Comment by dqbd** [comment]
Fixed in 0.0.31

**Comment by Nageswar-Sahoo** [comment]
I am using Rancher Desktop, but it seems that the auto code refresh feature is not working when I make changes in the cursor IDE. Do we need to modify any settings in Rancher Desktop for this? If anyone has information or suggestions, please share.
