### ISSUE TITLE
Feature Request: Add VSCodium Support

### ISSUE THREAD

**Issue by stephenl03** [langchain-ai/langgraph-studio#135]
**What**
- Detect if supported IDE is installed
- Display a dynamic button to launch supported IDE(s) or message to install VSCode/VSCodium
- Add VSCodium support

**Why**
- Improve user experience by displaying appropriate message/button
- Extend support to an additional IDE

**Additional Notes**
- VSCodium is typically a drop-in replacement to VSCode so extending support should be a low level of effort.
- When LangGraph Studio starts it should resolve the paths `/Applications/Visual Studio Code.app` and `/Applications/VSCodium.app` on MacOS and open the corresponding IDE if installed.
- I'm assuming a very similar process could be applied for other Operating Systems because they are both Electron apps.

**Comment by dqbd** [comment]
Should be resolved in 0.0.26!
