### ISSUE TITLE
cant easily edit lists

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langgraph-studio#137]
This screenshot shows trying to edit a list in the studio ui. It shows "no options available". this is suppose to be a list of arbitrary strings
![Screenshot 2024-09-27 at 3 06 42 PM](https://github.com/user-attachments/assets/ebb00adf-9fca-480c-9305-730eb93fd1db)

**Comment by dqbd** [comment]
Released in 0.0.28!
