### ISSUE TITLE
LangGraph Studio does not work anymore

### ISSUE THREAD

**Issue by colindaniels** [langchain-ai/langgraph-studio#145]
Worked previously, but after a LangGraph studio update was pushed, my unchanged typescript project will error out.

Troubleshooting steps already taken:
- Freshly cloned "react-agent-js" starter template from langgraphjs repo.
- Deleting all docker builds, volumes, images, and containers.
- Reinstalled langgraph studio
- Tried running without langgraph studio (compiling ts and running node), and it runs perfectly.

The project runs as it should, until I try using langgraph studio.

I get the following error:
langgraph-api-1       | Process SpawnProcess-1:
langgraph-api-1       | Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
langgraph-api-1       |     self.run()
langgraph-api-1       |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
langgraph-api-1       |     self._target(*self._args, **self._kwargs)
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
langgraph-api-1       |     target(sockets=sockets)
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
langgraph-api-1       |     return asyncio.run(self.serve(sockets=sockets))
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
langgraph-api-1       |     return runner.run(main)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
langgraph-api-1       |     return self._loop.run_until_complete(task)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
langgraph-api-1       |     await self._serve(sockets)
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
langgraph-api-1       |     config.load()
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
langgraph-api-1       |     self.loaded_app = import_from_string(self.app)
langgraph-api-1       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
langgraph-api-1       |     module = importlib.import_module(module_str)
langgraph-api-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
langgraph-api-1       |     return _bootstrap._gcd_import(name[level:], package, level)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
langgraph-api-1       |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
langgraph-api-1       |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
langgraph-api-1       |   File "/api/langgraph_api/server.py", line 14, in <module>
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 9, in <module>
langgraph-api-1       |   File "/api/langgraph_api/queue.py", line 15, in <module>
langgraph-api-1       |   File "/api/langgraph_api/shared/stream.py", line 21, in <module>
langgraph-api-1       |   File "/usr/local/lib/python3.12/site-packages/langgraph_storage/store.py", line 6, in <module>
langgraph-api-1       |     from langgraph.store.base import BaseStore, V
langgraph-api-1       | ImportError: cannot import name 'V' from 'langgraph.store.base' (/usr/local/lib/python3.12/site-packages/langgraph/store/base/__init__.py)

See picture below:

<img width="1428" alt="Screenshot 2024-09-30 at 8 51 27 PM" src="https://github.com/user-attachments/assets/50014d06-792b-46e2-ac6b-0bb4c2a946a3">

**Comment by adamterlson** [comment]
Yes! This is also my experience. No changes to my project and now things do not work. I want to add that I'm not using Typescript, and this error still occurs.

**Comment by DShomin** [comment]
I tried changing the python version and specifying the langgraph version of `requirements.txt`, but the same error is occurring. Maybe it's a problem with the distributed docker. It worked well until yesterday, but it's not working now.

**Comment by dastan92** [comment]
Getting the same error. Reinstalled dependencies. I am using python and getting the same error. Was working until 3 hours before.

**Comment by colindaniels** [comment]
Yeah, just switched over to python, still getting the same errors. This problem isn't exclusive to typescript. I'll change the title.

**Comment by rvndbalaji** [comment]
Im not using langgraph studio, but im using langgrapph in my python fast api server 
I got the exact same error
I upgraded every library below to the latest version and it started working. 
```

fastapi==0.115.0
uvicorn==0.31.0
transformers==4.45.1
numpy
pandas==2.2.3
python-jose[cryptography]
scikit-learn==1.5.2
langchain-community==0.3.1
langchain_google_community==2.0.0
langchain-google-vertexai==2.0.2
langchain==0.3.1
langchain-core==0.3.7
langchain-postgres==0.0.12
langchain_anthropic==0.2.1
langchain_experimental==0.3.2
langgraph==0.2.31
langfuse
anthropic[vertex]==0.34.2
google-api-core==2.20.0
google-cloud-storage==2.18.2
google-cloud-aiplatform==1.68.0
google-cloud-bigquery==3.26.0
grpcio==1.66.2
ipython
gcsfs
python-dotenv
requests
pydantic==2.9.2
PyMuPDF
unstructured
unstructured[all-docs]
pgvector
tiktoken
opencv-python
isort
chardet



```

**Comment by DShomin** [comment]
Oh it works well I fix the langgraph version to `requirements.txt` and it works fine. I used `langgraph==0.2.28` Thanks @rvndbalaji.

**Comment by dqbd** [comment]
Hello, we apologise for the inconvenience caused by a versioning bug. We've cut a new image which should address the issue. The API image should be pulled automatically by restarting the project or reopening Studio

**Comment by liezl200** [comment]
I'm getting issues now 
#7 8.754   Building wheel for tiktoken (pyproject.toml): started
#7 9.238   Building wheel for tiktoken (pyproject.toml): finished with status 'error'
#7 9.249   error: subprocess-exited-with-error
#7 9.249   
#7 9.249   × Building wheel for tiktoken (pyproject.toml) did not run successfully.
#7 9.249   │ exit code: 1
#7 9.249   ╰─> [38 lines of output]
#7 9.249       running bdist_wheel
#7 9.249       running build
#7 9.249       running build_py
#7 9.249       creating build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       copying tiktoken/load.py -> build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       copying tiktoken/core.py -> build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       copying tiktoken/__init__.py -> build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       copying tiktoken/registry.py -> build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       copying tiktoken/_educational.py -> build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       copying tiktoken/model.py -> build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       creating build/lib.linux-aarch64-cpython-311/tiktoken_ext
#7 9.249       copying tiktoken_ext/openai_public.py -> build/lib.linux-aarch64-cpython-311/tiktoken_ext
#7 9.249       running egg_info
#7 9.249       writing tiktoken.egg-info/PKG-INFO
#7 9.249       writing dependency_links to tiktoken.egg-info/dependency_links.txt
#7 9.249       writing requirements to tiktoken.egg-info/requires.txt
#7 9.249       writing top-level names to tiktoken.egg-info/top_level.txt
#7 9.249       reading manifest file 'tiktoken.egg-info/SOURCES.txt'
#7 9.249       reading manifest template 'MANIFEST.in'
#7 9.249       warning: no files found matching 'Makefile'
#7 9.249       adding license file 'LICENSE'
#7 9.249       writing manifest file 'tiktoken.egg-info/SOURCES.txt'
#7 9.249       copying tiktoken/py.typed -> build/lib.linux-aarch64-cpython-311/tiktoken
#7 9.249       warning: build_py: byte-compiling is disabled, skipping.
#7 9.249       
#7 9.249       running build_ext
#7 9.249       running build_rust
#7 9.249       error: can't find Rust compiler
#7 9.249       

...
Error invoking remote method 'up': ExecaError: Command failed with exit code 17: docker compose --project-directory /Users/lie/workspace/langchain-academy/module-1/studio --project-name studio-b40d0238b4f6c6c18cccdc8d13fabe025a664ea2d4bc2f368319ca9eb85c48ab -f - up --remove-orphans --watch

failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install -c /api/constraints.txt -r /deps/__outer_studio/src/requirements.txt" did not complete successfully: exit code: 1

#0 building with "desktop-linux" instance using docker driver

#1 [langgraph-api internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.10kB done
#1 WARN: JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 16)
#1 DONE 0.0s

#2 [langgraph-api internal] load metadata for docker.io/langchain/langgraph-api:3.11
#2 DONE 0.0s

#3 [langgraph-api internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [langgraph-api stage-0 1/7] FROM docker.io/langchain/langgraph-api:3.11
#4 DONE 0.0s

#5 [langgraph-api internal] load build context
#5 transferring context: 4.71kB done
#5 DONE 0.0s

#6 [langgraph-api stage-0 2/7] ADD requirements.txt /deps/__outer_studio/src/requirements.txt
#6 CACHED

**Comment by dqbd** [comment]
Hello @liezl200! This seems to be an upstream issue with tiktoken, which should be resolved. Do let us know if the issue still persists.
