### ISSUE TITLE
Environment variable value not being set in langgraph.json

### ISSUE THREAD

**Issue by turtle3791** [langchain-ai/langgraph-studio#146]
In project settings for environment variables I chose "Switch to values"
And entered GOOGLE_APPLICATION_CREDENTIALS for name and 
/deps/__outer_backend_py/src/gcp-bq-proj1.json for value

However looking at langgraph.json I do not see the variable value(path).
I only see the variable name (GOOGLE_APPLICATION_CREDENTIALS)

{
  "dockerfile_lines": [],
  "graphs": {
    "my_agent": "./my_agent/main.py:graph"
  },
  "env": [
    "GOOGLE_APPLICATION_CREDENTIALS"
  ],
  "python_version": "3.11",
  "dependencies": [
    "."
  ]
}

How do I provide environment variable value?

**Comment by dqbd** [comment]
Hello, when storing env variables as values, LangGraph Studio stores the values locally instead. This was done to prevent accidentally committing `.env` file. 

You can read/write the environment variables either via Studio > Project Settings or you can also switch to `.env` file by setting `"env": ".env"` in `langgraph.json`
