### ISSUE TITLE
Bug: When selecting EU region can not login on desktop client

### ISSUE THREAD

**Issue by gruckion** [langchain-ai/langgraph-studio#15]
Expected:
- Logging into any data region redirects you back to the desktop app to complete login.

Actual:
1. Log into desktop app
2. Continues to browser
3. Login with any OAuth provider on EU data region
4. Doesn't offer to take you back to app to complete login.
5. Have to repeat and stay selected on US to complete login.

**Comment by dqbd** [comment]
Hello @gruckion! Thank you for reporting the issue, will investigate into methods of improving the workflow for EU regions / self-hosted options.

In the meantime: you can login to EU region instead by:
1. Logging out of LangGraph Studio (see the attached image)
2. Visit `https://eu.smith.langchain.com/studio/auth`, which should relog you back to LangGraph Studio

![CleanShot 2024-08-02 at 01 57 51@2x](https://github.com/user-attachments/assets/e907b5f4-a655-4ae9-a939-4bb621406cc5)

**Comment by dqbd** [comment]
Fixed in 0.0.12
