### ISSUE TITLE
Docker authentication issues

### ISSUE THREAD

**Issue by mdean77a** [langchain-ai/langgraph-studio#153]
When I start fresh and it asks me to log in to Langsmith, it does not ask me for an account and password but automatically logs me in.  I can log in to LangSmith without problems.  But I get this error:

Failed to start project new-langgraph-project-3
Error invoking remote method 'up': ExecaError: Command failed with exit code 1: docker pull 'langchain/langgraph-api:3.11'

Error response from daemon: Head "https://registry-1.docker.io/v2/langchain/langgraph-api/manifests/3.11": unauthorized: incorrect username or password

**Comment by mdean77a** [comment]
On the startup page it offers me an authentication token and say "paste it into LangGraph Studio".  How do I paste a token into an application?

**Comment by dqbd** [comment]
Hello @mdean77a, this does indicate an authentication issue with your docker CLI. Would it be possible to log out and log in in Docker? 

```
docker logout
docker login
```

**Comment by mdean77a** [comment]
Thank you!  That worked.

- Mike

J. Michael Dean, MD, MBA
Professor Emeritus
Department of Pediatrics
University of Utah School of Medicine
Salt Lake City, Utah

Telephone: 801-739-4510 (mobile)

**Comment by dqbd** [comment]
Glad to hear that! Closing
