### ISSUE TITLE
Bug: `rerun` last message replays the wrong message

### ISSUE THREAD

**Issue by gruckion** [langchain-ai/langgraph-studio#16]
Expected:
- Rerun last message to actually run the last message.

Actual:
1. `[+ message]` enter `weather in SF`
2. `[edit]` enter `weather in DC`
3. `[rerun]` for `weather in DC` changes the message back to `weather in SF`

**Comment by hwchase17** [comment]
not sure i understand, are you able to share a loom or a video?
