### ISSUE TITLE
Support for asynchronous graph compilation

### ISSUE THREAD

**Issue by david1542** [langchain-ai/langgraph-studio#162]
Hi everyone :)

I'm currently creating my graph asynchronously, since I have to pull stuff from the database (information about the customers, API keys, etc).

Is it possible to make langgraph-studio support asynchronous graph compilation? Right now, I have to specify the file + variable of the graph in my `langgraph.json`.

It'd be cool if I could specify a function that compiles the graph. Namely, instead of this in my `langgraph.json`:

```json
{
  "graphs": {
    "my_graph": "./simple.py:graph"
  },
}
```

I could do this:
```json
{
  "graphs": {
    "my_graph": {
      "asyncLoader": "./simple.py:create_my_graph" 
     }
  },
}
```

**Comment by dqbd** [comment]
Hello! I believe it is possible to provide a function, which will return a compiled graph, both in Python and JS.

For the given example `"asyncLoader": "./simple.py:create_my_graph"`, make sure that the function is named `create_my_graph`

**Comment by ArxlanAli** [comment]
Hi, We don't need to specify `asyncLoader` anymore, simple give path of agent file as a string.

Below is my `langgraph.json` file.

```
{
  "dockerfile_lines": [],
  "graphs": {
    "agent_graph": "./src/agent_graph.ts:graph"
  },
  "env": ".env",
  "node_version": "20"
}
```

And here is my definition of compilation graph.

```
export const graph = async () => {
  await checkpointer.setup();
  return workflow
    .compile({
      checkpointer,
    })
    .withConfig({ runName: "AgentGraph" });
};
```
