### ISSUE TITLE
Feature: yaml state syntax highlighting

### ISSUE THREAD

**Issue by gruckion** [langchain-ai/langgraph-studio#17]
<img width="1205" alt="image" src="https://github.com/user-attachments/assets/fa4ed248-a546-4b8a-aaa2-fc34d2af2c4f">

Has syntax highlighting for JSON but not for Yaml.

- Open to submitting a PR for this but langgraph-studio isn't OSS

**Comment by dqbd** [comment]
Fixed in 0.0.20
