### ISSUE TITLE
Authentication Bug - Version 0.0.28

### ISSUE THREAD

**Issue by HartmanAnalytics** [langchain-ai/langgraph-studio#174]
Using LangSmith to authenticate does not work properly when opening a project locally using LangGraph Studio

Steps to reproduce:
- Download Langgraph here: https://langgraph-studio.vercel.app/api/mac/latest
- Update to 0.0.28 via the client as the above link actually points to the previous version (LangGraph-Studio-0.0.27-universal.dmg)
- Start Docker Desktop, ensure latest versions
- Open LangGraph Studio Client
- Authenticate via Langsmith
- Open project

Steps to try to solve:
- Cleared all existing containers, images, volumes and builds in Docker Desktop
- Verified latest versions for docker and docker-compose
- Checked that key was successfully added in LangSmith
- Re-installed LangGraph Studio from scratch. 
- Logged out and logged back in (which generates a new key in LangSmith)
- Verified that no existing or conflicting keys are in `.zshrc` or `.zprofile`

Log:
```
langgraph-api-1       | info | Will watch for changes in these directories: ['/deps/__outer_Danzek/Danzek']
langgraph-api-1       | info | Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
langgraph-api-1       | info | Started reloader process [1] using StatReload
langgraph-api-1       | info | Started server process [8]
langgraph-api-1       | info | Waiting for application startup.
langgraph-api-1       | warning | No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment.
langgraph-api-1       | info | HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 403 Forbidden"
langgraph-api-1       | error | Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/lifespan.py", line 18, in lifespan
ValueError: License key is not valid

langgraph-api-1       | error | Application startup failed. Exiting.
```
![Screenshot 2024-10-26 at 8 50 00 AM](https://github.com/user-attachments/assets/3af46812-9eaa-41ff-96ec-8c851fbb8e03)

![Screenshot 2024-10-26 at 8 56 02 AM](https://github.com/user-attachments/assets/17804bff-3c05-4cc2-ab0d-0afee9a6dfc3)

![Screenshot 2024-10-26 at 8 56 07 AM](https://github.com/user-attachments/assets/3abedf28-a23c-49c7-b287-14a1e05de720)

![Screenshot 2024-10-26 at 9 06 20 AM](https://github.com/user-attachments/assets/8aeaec2f-7e65-466d-93cb-136337b0f581)

**Comment by notintricate** [comment]
Same problem

**Comment by dqbd** [comment]
Hello! We've released a new version of Studio: 0.0.31, which will highlight if the API key becomes invalid. 

If the issue still persists, please check if your `.env` file does not contain any LANGCHAIN_/LANGSMITH_ API keys, these are being inserted automatically by Studio

Feel free to reopen the issue if the problem still persists.

**Comment by adeel2020** [comment]
<img width="1464" alt="image" src="https://github.com/user-attachments/assets/8427e923-4c82-4b75-9196-7f539260f247" />
Every Time when i am logging in and logging out, a new API key is generated. But the one i manually created is not working and still getting the same error 


- For local development, set a valid LANGSMITH_API_KEY for an account with LangGraph Cloud access in the environment defined in your langgraph.json file.

**Comment by gupta-bhavesh** [comment]
Facing the same issue. Any solutions??
I am on a normal developer plan and haven't entered card details yet. Is that the issue?
Both automatically setting of LANGSMITH_API_KEY and manually setting it didn't worked

**Comment by dqbd** [comment]
> @adeel2020: Every Time when i am logging in and logging out, a new API key is generated. But the one i manually created is not working and still getting the same error

Could you check if you don't have a `LANGSMITH_ENDPOINT` or `LANGSMITH_API_KEY` environment variable set in your `.env` file or your system env vars?

Studio Desktop will automatically insert those env vars for your, so you don't need to provide these env vars yourself.

**Comment by dqbd** [comment]
> @gupta-bhavesh Facing the same issue. Any solutions?? I am on a normal developer plan and haven't entered card details yet. Is that the issue? Both automatically setting of LANGSMITH_API_KEY and manually setting it didn't worked

Studio Desktop does not require any payment nor upgrade to LangSmith Plus. In most cases would check, if you haven't specified `LANGSMITH_ENDPOINT` or `LANGSMITH_API_KEY` in your .env file
