### ISSUE TITLE
Hot Reload is not working for python

### ISSUE THREAD

**Issue by nehiljain** [langchain-ai/langgraph-studio#177]
Hot reloading is not working with langgraph studio. When I change code, I have to kill docker compose and rebuild everything. Please help.

Similar issue mentioned in slack: https://langchaincommunity.slack.com/archives/C06PTQF6MCK/p1728024501374669

**Comment by dqbd** [comment]
Hello @nehiljain! Usually the main culprit is the old version of Docker Desktop / Docker Compose. We recommend upgrading your Docker version to latest in order to get Compose to version 2.25.0+
