### ISSUE TITLE
How to add other volume paths to Lang graph Studio

### ISSUE THREAD

**Issue by alew3** [langchain-ai/langgraph-studio#178]
I want to add a LanceDB database that is not inside the langgraph project folder. How can we add other volumes to the Docker? I didn't see the docker configurations exposed.

**Comment by dqbd** [comment]
Hello! You should be able to specify `docker_compose_file` in your `langgraph.json` to extend our Compose stack.

```
services:
  langgraph-api:
    ...

volumes:
  ...
```
