### ISSUE TITLE
Project Error: Failed to fetch 

### ISSUE THREAD

**Issue by thebhulawat** [langchain-ai/langgraph-studio#18]
Project is not starting because of the error and I am unable to move past this screen. 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/5525e8ca-de76-4f18-8798-9a6a6587dda3">

**Comment by dqbd** [comment]
Hello! Just to clarify: does this issue clear itself out after restarting the service?

**Comment by thebhulawat** [comment]
Tried restarting the service multiple times. I am using langchain-example project for now. Getting this now - 
<img width="628" alt="image" src="https://github.com/user-attachments/assets/00c2911c-d1a9-4cfc-bc83-3338550740d4">

**Comment by dqbd** [comment]
Should be fixed with 0.0.19! Feel free to reopen if the issue still persists

**Comment by johannescastner** [comment]
I'm getting this problem now!  Failed to load assistant schema. TypeError: Failed to fetch
