### ISSUE TITLE
Dependency Conflict in Docker Build

### ISSUE THREAD

**Issue by RashidSM** [langchain-ai/langgraph-studio#19]
![Screenshot 2024-08-02 at 12 51 04](https://github.com/user-attachments/assets/9b92fef7-119a-407c-b216-04be983ac8e5)

When building the Docker image using the provided Dockerfile, a dependency conflict occurs due to version constraints specified for the langgraph package.

Suggested Solutions:
Loosen the range of package versions specified in constraints.txt.

**Comment by hwchase17** [comment]
Unfortunately we rely on newer versions of langgraph (which enable a lot of this). Are you able to bump or loosen the dependencies in your project?

**Comment by RashidSM** [comment]
As I'm using the langgraph-example code, the requirements.txt is sourced from the example repository, and there is no specific version specified for langgraph.
[requirements.txt](https://github.com/user-attachments/files/16472597/requirements.txt)

**Comment by RashidSM** [comment]
i also tried fixing the version to 0.1.19.

**Comment by RashidSM** [comment]
Setting the version to the latest in the requirements.txt resolved the issue for now.
