### ISSUE TITLE
Subgraph is not working correctly in Studio

### ISSUE THREAD

**Issue by farhang103** [langchain-ai/langgraph-studio#190]
When from parent graph goes to the subgraph, the chat is only showing null output for the subgraph node even though in LangSmith it shows that it's not null and working

**Comment by bforbanks** [comment]
I have the same problem. It makes langgraph unusable with subgraphs

**Comment by Glavin001** [comment]
Does the pre-release 0.0.31 fix it for you? https://github.com/langchain-ai/langgraph-studio/releases/tag/v0.0.31

I had an issue which sounded similar and the pre-release fixed it.

**Comment by bforbanks** [comment]
I dont have a MacOS so i can't test it. I'm using the new `langgraph dev`, with the langsmith hosted version of Langgraph Studio

**Comment by anmol-aidora** [comment]
I am also facing a similar problem. Mentioned in the issue #197 .

**Comment by dqbd** [comment]
Hello! The fix for subgraphs should be now live for langsmith hosted version of LangGraph. Feel free to reopen the issue if the problem still persists

**Comment by farhangDatafinery** [comment]
> Hello! The fix for subgraphs should be now live for langsmith hosted version of LangGraph. Feel free to reopen the issue if the problem still persists

What about Studio? The problem that I have is on local

**Comment by dqbd** [comment]
> > Hello! The fix for subgraphs should be now live for langsmith hosted version of LangGraph. Feel free to reopen the issue if the problem still persists
> 
> What about Studio? The problem that I have is on local

Version 0.0.31 of Desktop Studio should include the fix as well
