### ISSUE TITLE
Collapse long text

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langgraph-studio#196]
Problem
My current graph has fields with long text values so when the node outputs those values the thread list becomes difficult to navigate (screenshot #2). I need to scroll up for a while until I see the field collapse :arrow_down_small:  button (screenshot #1).
Proposed Solution
Could be a "collapse all" button or when hovering show a collapse :arrow_down_small: button inline (to the left, etc) which is always visible without requiring to scroll up a lot

**Comment by dqbd** [comment]
Will be solved in next version of Studio

https://github.com/user-attachments/assets/f354d294-055f-44d5-8c79-86aad109545e
