### ISSUE TITLE
How is state schema read by studio?

### ISSUE THREAD

**Issue by shivangag** [langchain-ai/langgraph-studio#22]
I've define two state schema, InputState and OutputState, using langchain.pydantic_v1 BaseModel.

For
`workflow = StateGraph(input=InputState, output=OutputState)
`
I'm actually shown OutputState schema as Input in Studio UI.

So I've to do
`workflow = StateGraph(input=OutputState, output=InputState)
`
to get correct input.

Moreover, if I've a BaseAgentState that contain some common state for all my graphs, and if I'm extending this to add new states in  any given graph, Studio UI is not able to show it correctly.

Is there any other way to abstract out common states?

Here is an example:
```
class BaseAgentState(BaseModel):
    name: str
    org_name: str

    context: Annotated[
        AgentContext, Context(make_context)
    ] = Field(exclude=True)
    messages: Annotated[List[BaseMessage], add_messages] = Field(default_factory=list)
```

```
class InputState(BaseAgentState):
    new_state: str
```

**Comment by hwchase17** [comment]
thanks for flagging - its a known issue that we don't properly support input/output schema, this is top of our roadmap! sorry for inconvience and thanks for patience

**Comment by hwchase17** [comment]
Closing in favor of #29
