### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by berkybear** [langchain-ai/langgraph-studio#23]

**Comment by dqbd** [comment]
Linux and other platforms are on our roadmap! We'll keep you posted!

**Comment by Sebastiaan76** [comment]
+1 on this. Not sure why in this day and age you wouldn't just make this cross-platform from the get-go. Good to hear it's on the roadmap though! Will await the Linux binaries!

**Comment by hemangjoshi37a** [comment]
Here is a great alternative to this.https://github.com/microsoft/autogen/tree/main/samples/apps/autogen-studio

**Comment by JovanNj** [comment]
Any news on this? When can we expect it?

**Comment by tushar-madheshia** [comment]
@dqbd is there any ETA you have for this?

**Comment by hinthornw** [comment]
Hi all! As mentioned in the [other thread](https://github.com/langchain-ai/langgraph-studio/issues/63#issuecomment-2489918221) and ([in the docs](https://langchain-ai.github.io/langgraph/how-tos/local-studio/), we now support a similar experience using the:

```shell
langgraph dev
```
command.

We don't have near-term plans to develop a desktop application for linux; instead we want to ensure we support the same functionality through the CLI + web UI.
