### ISSUE TITLE
Update docs: Docker requirements

### ISSUE THREAD

**Issue by stephenl03** [langchain-ai/langgraph-studio#24]
The documentation and previous issues state Docker Desktop is required but it appears that there are minimum version requirements and the docker and docker-* commands need to be in the PATH for langgraph-studio to leverage them. I propose the documentation be updated to be more transparent with the minimum requirements needed and additional steps to validate the minimum requirements.

For example, validate docker-compose version 2.22.0+ https://github.com/langchain-ai/langgraph-studio/issues/5#issuecomment-2264181725
Verify docker and docker-* executable files are in `/usr/local/bin`
```
ll /usr/local/bin/docker*
lrwxr-xr-x  1 root  wheel    80B Aug  2 12:20 /usr/local/bin/docker -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker
lrwxr-xr-x  1 root  wheel    87B Aug  2 12:24 /usr/local/bin/docker-buildx -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-buildx
lrwxr-xr-x  1 root  wheel    88B Aug  2 12:20 /usr/local/bin/docker-compose -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-compose
lrwxr-xr-x  1 root  wheel   101B Aug  2 12:24 /usr/local/bin/docker-credential-ecr-login -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-credential-ecr-login
lrwxr-xr-x  1 root  wheel    96B Aug  2 12:24 /usr/local/bin/docker-credential-none -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-credential-none
lrwxr-xr-x  1 root  wheel   103B Aug  2 12:24 /usr/local/bin/docker-credential-osxkeychain -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-credential-osxkeychain
``` 

The above resolved the errors below for me
```
Docker not installed or not running: ExecaError: Command failed with ENOENT: docker info -f json
error getting credentials - err: exec: "docker-credential-osxkeychain": executable file not found in $PATH, out: ``
```

The licensing associated with Docker Desktop has pushed many people to other options that might meet the underlying requirements.

**Comment by dqbd** [comment]
Hello! By default we'll try to find the PATH env value by figuring out what default shell you've setup and then run `[shell] -lc 'echo $PATH'`. Could you try running the command to see if `docker` is present in that PATH?

**Comment by hwchase17** [comment]
Agree with comments on documentaiton though, will update to reflect docker-compose

**Comment by hwchase17** [comment]
changed in https://github.com/langchain-ai/langgraph-studio/pull/26

**Comment by stephenl03** [comment]
@dqbd Here is the output from the command [1]. I had symlinks originally in `/Users/<redacted>/.rd/bin/* -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/*` for docker and docker-* commands but LangGraph Studio wasn't able to pick up on them. 

[1]
```
> $SHELL -lc 'echo $PATH'
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/<redacted>/.nvm/versions/node/v22.4.1/bin:/Users/<redacted>/.rd/bin:/Users/<redacted>/google-cloud-sdk/bin:/Users/<redacted>/.pyenv/shims:/Users/<redacted>/.local/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/Applications/iTerm.app/Contents/Resources/utilities
```
