### ISSUE TITLE
Feature: x-ray mode for subgraphs

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langgraph-studio#32]
support inspecting sub graphs in the UI

**Comment by Glavin001** [comment]
Need this! Is there an ETA?

## Steps to reproduce:
Using example https://langchain-ai.github.io/langgraph/how-tos/subgraph/?h=subgraph#simple-example

| LangGraph Studio | `draw_mermaid_png` |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5fd62df7-c789-4114-b1a4-fc4f249ab649) | ![image](https://github.com/user-attachments/assets/fda052fe-3fda-4a2e-921c-2de3f81c3d09) |

**Comment by HyunjunJeon** [comment]
+1 =D

**Comment by juandiegobalbi** [comment]
Any idea if this is coming anytime soon?

**Comment by arthberman** [comment]
@dqbd any ETA date ? :)

**Comment by dqbd** [comment]
Released in 0.0.28!
