### ISSUE TITLE
Bug: can't start the project

### ISSUE THREAD

**Issue by Nov1c444** [langchain-ai/langgraph-studio#37]
I got the issue, But my docker is running, and I can get the result when I exec the command **docker info -f json**
> Failed to start project langgraph-example
> Docker not installed or not running: ExecaError: Command failed with ENOENT: docker info -f json
> spawn docker ENOENT
<img width="729" alt="image" src="https://github.com/user-attachments/assets/53595f7d-bd21-4aa5-bd2b-08eeae7fcf7f">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/84cbb48d-4b1f-4ecc-bc82-0fc07b26011e">

**Comment by gerardsimons** [comment]
I am having the same issue, just upgraded my Docker too :

```
> docker version
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:54:12 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.33.0 (160616)
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:14 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by nargetdev** [comment]
Same issue here

**Comment by nargetdev** [comment]
I don't actually know whether it was the `chsh` that fixed it or just opening from zsh ... but this worked:

      
      ⟩ chsh -s /bin/zsh
      Changing shell for mswhiskers.
      Password for mswhiskers:
      
      ~
      ⟩ /bin/zsh
      
      ➜  ~
      ➜  ~
      ➜  ~ echo $SHELL
      /opt/homebrew/bin/fish
      ➜  ~ /Applications/LangGraph\ Studio.app
      ➜  LangGraph Studio.app open .
      ➜  LangGraph Studio.app

**Comment by gerardsimons** [comment]
@nargetdev Nice one, can confirm this works for me too, was also using fish so that seems to be the issue. As an easy one-liner alternative you can also do:

`/bin/zsh -c 'open /Applications/LangGraph\ Studio.app/'`

**Comment by Nov1c444** [comment]
> @nargetdev Nice one, can confirm this works for me too, was also using fish so that seems to be the issue. As an easy one-liner alternative you can also do:
> 
> `/bin/zsh -c 'open /Applications/LangGraph\ Studio.app/'`

thanks, it works for me

**Comment by whamsicore** [comment]
thx guys, fixed for me too

**Comment by AnhDungPham2901** [comment]
> @nargetdev Nice one, can confirm this works for me too, was also using fish so that seems to be the issue. As an easy one-liner alternative you can also do:
> 
> `/bin/zsh -c 'open /Applications/LangGraph\ Studio.app/'`

Thanks a lot

**Comment by jacopo-chevallard** [comment]
Thanks for the solution!

**Comment by stevenjhammond** [comment]
> @nargetdev Nice one, can confirm this works for me too, was also using fish so that seems to be the issue. As an easy one-liner alternative you can also do:
> 
> `/bin/zsh -c 'open /Applications/LangGraph\ Studio.app/'`

This worked for me too. Thanks!

**Comment by dipanjan77** [comment]
It fixed for me. But curious to know why opening LangGraph from Apps directly always shows the docker error, but opening the app from zsh solves the problem? Is there a configuration in the app, that could be set to use zsh directly?

**Comment by nargetdev** [comment]
> It fixed for me. But curious to know why opening LangGraph from Apps directly always shows the docker error, but opening the app from zsh solves the problem? Is there a configuration in the app, that could be set to use zsh directly?

if your default shell is fish then I think opening from Apps is using that shell. If you try `chsh -s $(which zsh)` and then logout // log back in then opening form Apps will work.
