### ISSUE TITLE
Can't get langgraph-example to open

### ISSUE THREAD

**Issue by pluggedinn** [langchain-ai/langgraph-studio#4]
I followed the instructions from this video from the official youtube channel. [here](https://www.youtube.com/watch?v=pLPJoFvq4_M) and I'm getting error ```Failed to start project langgraph-example
Docker not installed or not runningSyntaxError: Unexpected token 'j', "json" is not valid JSON```

<img width="1211" alt="Screenshot 2024-08-01 at 2 37 51 PM" src="https://github.com/user-attachments/assets/d102522a-9a51-4110-be8e-094657688d74">

I have docker running version 20.10.21 that I installed using brew. Trying to run this on MacBook Pro 14" M1.

**Comment by dqbd** [comment]
Hello @pluggedinn! Currently we only support Docker Engine 25.x.x and higher. Would it be possible to upgrade Docker and retry?

**Comment by dqbd** [comment]
Added additional checks in 0.0.11, feel free to reopen if the issue still persist after updating Docker!

**Comment by pluggedinn** [comment]
updating worked. thank you!
