### ISSUE TITLE
Not working when using Docker Emulation with Podman

### ISSUE THREAD

**Issue by deanchanter** [langchain-ai/langgraph-studio#40]
![image](https://github.com/user-attachments/assets/9ebb7340-378b-4bcd-8b27-7b745c9abd25)

**Comment by dqbd** [comment]
Hello @deanchanter! Podman is currently unsupported at the moment, but will look into it!

**Comment by dyingc** [comment]
Yes, hit exactly the same issue! I can't use docker in our Mac so Podman is my only option :-(

**Comment by sky-victortavernari** [comment]
Docker is not free, so because of that I can't use it :( 
I have to wait for the podman integration.

**Comment by alew3** [comment]
any updates on this?

**Comment by and1412** [comment]
any updates on this?

**Comment by ultrasonex** [comment]
Same here. Need podman support for running studio.

**Comment by dqbd** [comment]
Hello! We've recently released a new improved version of LangGraph CLI, which does not rely on Docker for local development!<br><br>See [https://langchain-ai.github.io/langgraph/how-tos/local-studio/](https://langchain-ai.github.io/langgraph/how-tos/local-studio/) for more information.<br><br>Will close the issue for now, feel free to reopen if CLI doesn't suit your needs!

**Comment by jillesca** [comment]
Supporting Podman would be awesome, I had to switch from docker to podman on my work and seems that langgraph (cli `langgraph up`) and langgraph studio are heavily reliant on docker only.
