### ISSUE TITLE
Automatically sending traces to LangSmith

### ISSUE THREAD

**Issue by Nachoeigu** [langchain-ai/langgraph-studio#43]
Hi, I saw that LangGraph API is sending events to LangSmith in spite of removing my credentials (also LANGCHAIN_TRACING_V2) from the .env file.

I think the app maps my email and send the events anyway, beyond if my credentials are present or not in the env file. I think it is a bug. I also see that it send the traces in the project "default", that I never defined.

Thank you.

**Comment by dqbd** [comment]
Hello @Nachoeigu! Currently, LangGraph Studio will pre-populate both the API key and the `LANGCHAIN_TRACING_V2=true` when starting a folder. We also automatically create an API key when logging in.

**Comment by hwchase17** [comment]
The `default` project is a default project in LangSmith that exists as soon as you create an account. We will work on adding an option to opt-out of logging to LangSmith

**Comment by addrissio** [comment]
actually to disable the trace set in top of the file you're working on:

from dotenv import load_dotenv
import os

os.environ["LANGCHAIN_TRACING_V2"] = "false"
os.environ["LANGCHAIN_ENDPOINT"] = ""
os.environ["LANGCHAIN_API_KEY"] = ""
os.environ["LANGCHAIN_PROJECT"] = ""
