### ISSUE TITLE
neo4j integration

### ISSUE THREAD

**Issue by laBruji** [langchain-ai/langgraph-studio#44]
Hi! I'm trying to use Langgraph Studio for an agent that integrates with a neo4j database. Is there a way of modifying the docker image to open the neo4j proxy? Otherwise, I can't connect to the database

**Comment by dqbd** [comment]
Hello @laBruji! You can add additional Dockerfile lines by adding those in `langgraph.json` file, like so:

```json
{
  ...
  "dockerfile_lines": [
       "RUN pip install -U langgraph==0.1.19"
  ],
  ...
}
```

If your goal is to access services on your host, you can use the `host.internal.docker` DNS name ([see Docker docs](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host)) to access your Neo4j instance on the host.

Adding support for additional services in `docker-compose` is not yet supported, but on our roadmap!

**Comment by jpetrantoni** [comment]
Why not allow to run the graph as an api and langstudio connects to it? We are having alot of issues trying to get the agent running in your preset docker config

**Comment by dqbd** [comment]
Accessing external services should be possible as well. Closing this issue for now! Feel free to reopen if needed
