### ISSUE TITLE
Project fails to start

### ISSUE THREAD

**Issue by tmyracle** [langchain-ai/langgraph-studio#48]
I'm trying to run an implementation of the STORM graph in LangGraph Studio for debugging and currently running into the following issue:

```
#6 [langgraph-api 3/3] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
#6 0.857 ERROR: /deps/* is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
#6 0.995 
#6 0.995 [notice] A new release of pip is available: 24.0 -> 24.2
#6 0.995 [notice] To update, run: pip install --upgrade pip
#6 ERROR: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1
------
 > [langgraph-api 3/3] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*:
0.857 ERROR: /deps/* is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
0.995 
0.995 [notice] A new release of pip is available: 24.0 -> 24.2
0.995 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1
```

langgraph.json:
```json
{
  "dependencies": [
    "langchain_openai",
    "langchain_community",
    "langchain_core",
    "langgraph",
    "numpy",
    "asyncio",
    "python-dotenv",
    "wikipedia",
    "tavily-python"
  ],
  "graphs": {
    "my_graph_id": "./agent.py:storm_agent"
  },
  "env": "./.env"
}
```

in agent.py i'm compling the graph as follows:
```python
storm_agent = builder_of_storm.compile(checkpointer=MemorySaver())
```

LangGraph Studio: 0.0.11
Docker Desktop: 4.32.0
Macbook Pro M1 on Sonoma 14.1.1

It looks like it was able to successfully install all of my dependencies and then it runs into this issue. I wasn't sure where to look next to troubleshoot this so any help would be greatly appreciated! Let me know if there's anything else I can provide.

**Comment by hwchase17** [comment]
looking into fixing and/or a better error message. in the mean time, if you put those dependencies in a requirements.txt file and reference that in deps `["."]` that should work

**Comment by tmyracle** [comment]
Thanks Harrison, I moved them into a requirements.txt file and changed dependencies to ["."] and now it looks like its not installing the dependencies because I'm getting:

```
8           from langchain_openai import ChatOpenAI
#7 1.238       ModuleNotFoundError: No module named 'langchain_openai'
#7 1.238       [end of output]
```

and I made sure that the langchain packages are specified with underscores like in [the example project](https://github.com/langchain-ai/langgraph-example/tree/main)

my basic project structure is:
/storm_agent
  agent.py
  generate_outline.py
  generate_article.py
  langgraph.json
  requirements.txt
  
 I'm sure I'm doing something dumb, just unclear what that is 😅

**Comment by pluggedinn** [comment]
I've had similar issues and it was caused by the presence of pyproject.toml taking priority over requirements.txt. @tmyracle Do you happen to have a a pyproject.toml in the folder where you agent is?

**Comment by tmyracle** [comment]
@pluggedinn nope, there's one elsewhere in the repo but in the folder for I'm pointing LangGraph studio to I only have the following:

![CleanShot 2024-08-07 at 14 00 47](https://github.com/user-attachments/assets/8e1b3d53-77b8-4c71-a97c-0a496cca218e)

**Comment by hwchase17** [comment]
i think setup.py may be taking precendence over requirements.txt as well. Can you try either removing that OR putting the packages you want to install in setup.py?

**Comment by tmyracle** [comment]
@hwchase17 yep that fixed the dependencies not installing, just had to rename that file. Thanks for your help, I knew it was me doing something dumb :)
