### ISSUE TITLE
JS Support

### ISSUE THREAD

**Issue by nivo33** [langchain-ai/langgraph-studio#49]
Does langraph cloud / IDE only support python apps? Any plans / timeline for supporting JS?

**Comment by dqbd** [comment]
JS support is on our roadmap! Will keep you posted!

**Comment by TimSusa** [comment]
Maybe it would make sense to announce that in your readme, as personally, I lost a little time with the issue and coming as well again to the result, that JS/TS Users are one step behind.. concerning langchain in general, but yea that seems like it is.

**Comment by dqbd** [comment]
Supported with 0.0.18!
