### ISSUE TITLE
Missing environment var causes login to hang with no visible error

### ISSUE THREAD

**Issue by bwhiting2356** [langchain-ai/langgraph-studio#50]
I opened the langgraph-example repo in langgraph studio. I was initially missing a `.env` file in `langgraph-example`, I got a warning to fix it, and added one with an openai key, but neglected to add a tavily key. When I opened the repo again, login just hanged with no error, and I only saw the issue after opening the logs. It would be nice if the missing environment variable error was surfaced at the login step in the same way that the missing .env file error was surfaced.

**Comment by dqbd** [comment]
Should be fixed with 0.0.18!
