### ISSUE TITLE
Display langsmith trace  link on submit in playground 

### ISSUE THREAD

**Issue by hinthornw** [langchain-ai/langgraph-studio#55]
When I click"submit", would be nice to see a link to the langsmith trace immediately. Rn i have my project open in another tab and am hitting refresh. Reason is I have a lot of stuff within each node that I want to track (e.g., LLM calls)

**Comment by dqbd** [comment]
The button for opening LangSmith trace should appear next to the run after the run has been ingested

![CleanShot 2024-08-21 at 22 54 23@2x](https://github.com/user-attachments/assets/40984336-dc55-4869-9512-639497ebf9ee)
