### ISSUE TITLE
Application startup breaks with failed db migration

### ISSUE THREAD

**Issue by lfnovo** [langchain-ai/langgraph-studio#58]
This was working fine a while ago and now I am stuck with this issue when loading my app.  

```
graph-api-1       | 2024-08-08T14:33:51.292685Z [info     ] Started server process [8]     [uvicorn.error] api_revision=3d20975 api_variant=licensed color_message=Started server process [%d] desktop=0.0.11 filename=server.py func_name=_serve lineno=82
langgraph-api-1       | 2024-08-08T14:33:51.292780Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=3d20975 api_variant=licensed desktop=0.0.11 filename=on.py func_name=startup lineno=48
langgraph-api-1       | 2024-08-08T14:33:51.292948Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=3d20975 api_variant=licensed desktop=0.0.11 filename=validation.py func_name=get_license_status lineno=80
langgraph-api-1       | 2024-08-08T14:33:51.614934Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=3d20975 api_variant=licensed desktop=0.0.11 filename=_client.py func_name=_send_single_request lineno=1773
langgraph-api-1       | 2024-08-08T14:33:51.771424Z [error    ] migrate:  Usage: migrate [OPTIONS]
langgraph-api-1       | Try 'migrate --help' for help.
langgraph-api-1       | 
langgraph-api-1       | Error: No such option: -p [langgraph_storage.database] api_revision=3d20975 api_variant=licensed desktop=0.0.11 filename=database.py func_name=migrate lineno=69
langgraph-api-1       | 2024-08-08T14:33:51.772499Z [error    ] Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 730, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 19, in lifespan
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/langgraph_storage/database.py", line 72, in migrate
langgraph-api-1       |     raise RuntimeError(
langgraph-api-1       | RuntimeError: migrate failed Usage: migrate [OPTIONS]
langgraph-api-1       | Try 'migrate --help' for help.
langgraph-api-1       | 
langgraph-api-1       | Error: No such option: -p
langgraph-api-1       |  [uvicorn.error] api_revision=3d20975 api_variant=licensed desktop=0.0.11 filename=on.py func_name=send lineno=121
langgraph-api-1       | 2024-08-08T14:33:51.772649Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=3d20975 api_variant=licensed desktop=0.0.11 filename=on.py func_name=startup lineno=59
```

**Comment by hwchase17** [comment]
hi @lfnovo - sorry for this, can you try upgrading to the new 0.12 release and trying agian? we were in the process of releasing a new version and i think we miscoordinated some things. Can you try and let me know if that fixes it?

**Comment by lfnovo** [comment]
Hey @hwchase17  ... new version didn't fix it.. 

Running on 0.0.12 (0.0.12)

Failed to start project merovingian-os-take2
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 730, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/lifespan.py", line 19, in lifespan
  File "/usr/local/lib/python3.11/site-packages/langgraph_storage/database.py", line 72, in migrate
    raise RuntimeError(
RuntimeError: migrate failed Usage: migrate [OPTIONS]
Try 'migrate --help' for help.

Error: No such option: -p

Application startup failed. Exiting.

-- langgraph.json
```

{
  "python_version": "3.11",
  "dockerfile_lines": [],
  "dependencies": [
    "."
  ],
  "graphs": {
    "tool_agent": "./merovingian/graphs/tool_agent.py:tool_agent_graph\""
  },
  "env": ".env"
}
```

**Comment by lfnovo** [comment]
FWIW, tried deleting the docker containers and volumes to recreate. Didn't help either.

**Comment by hwchase17** [comment]
@lfnovo when i had this, i **think** i fixed it `docker system prune -f` and it fixed it. I wish i had a better solution since that's obviously not a good one. I'm guessing theres some containers/volumes that are not getting cleaned up... @nfcampos any ideas?

**Comment by lfnovo** [comment]
@hwchase17 .. nope.. that didn't do it.. 

Any idea of where this migrate -p come from? seems like -p is an invalid argument to it.

**Comment by nfcampos** [comment]
@lfnovo hi we don't pass a -p flag to migrate (which as you say doesn't exist). I've published a new build with more details in these logs, if you could update (restart the app) and re-send us the logs we can investigate more from there

**Comment by lfnovo** [comment]
@nfcampos Hey, there seems to be a new line in the debug log now.

migrate -path=/storage/migrations -database=postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable up 

If that is golang-migrate, perhaps the right syntax would be:

migrate -path ./storage/migrations -database "postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable" up

(notice the quotes on the db and the lack of equal sign)

**Comment by nfcampos** [comment]
The equals sign is supported, see golang migrate docs/help https://github.com/golang-migrate/migrate/tree/master/cmd/migrate or golang flag docs (used by migrate to parse argv) https://pkg.go.dev/flag (not to mention it works in our tests and for other folks)

I'll remove usage of golang migrate, which should hopefully fix this issue, will publish a new release shortly

**Comment by nfcampos** [comment]
Just published new version, do you want to try that one?
