### ISSUE TITLE
Should one create a .venv and install Requirements?

### ISSUE THREAD

**Issue by JacobGoldenArt** [langchain-ai/langgraph-studio#6]
Quick question about setup. Are the requirements installed via LangGraph Studio? Or would I still
want to create a .venv and pip install the requirements via vscode? bonus: If I want to add more python packages done the line, would I just add them to the requirements or do a pip install?
Thanks!

**Comment by hwchase17** [comment]
LangGraph studio will build its own environment based on requirements.txt (or pyproject.toml). if you want to run it outside the studio, you will want to build a .venv. But LangGraph Studio builds it own environment - so it will not know of anything in the .venv that does not come from requirements.txt/pyproject.toml

**Comment by JacobGoldenArt** [comment]
Thanks! I've got it working but when I look at the source code in vscode it's complaining that certain packages aren't installed so I think I will just create a .venv and pip install the requirements in .venv as well (and try to keep both in sync). I'm not sure how vscode could utilize the docker .env that studio uses but that would could be a nice feature in the future.
