### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by whamsicore** [langchain-ai/langgraph-studio#65]
<img width="726" alt="Screenshot 2024-08-10 at 6 55 55 PM" src="https://github.com/user-attachments/assets/76e665dc-b362-4a8e-a0a9-c06abf766a8f">

the error:
Docker not installed or not running: ExecaError: Command failed with ENOENT: docker info -f json
spawn docker ENOENT

I have docker desktop installed, fine. 

> docker --version
Docker version 27.1.1, build 6312585
> docker-compose --version
Docker Compose version v2.29.1-desktop.1

> ll /usr/local/bin/docker*
shows all the docker* executables are present

What's going on?

My docker installation is on mac silicon, if that's relevant?

**Comment by hwchase17** [comment]
Does the fix for this issue also help here? https://github.com/langchain-ai/langgraph-studio/issues/37

**Comment by whamsicore** [comment]
@hwchase17 thx, fixed! yeah, fish was what we had in common!
