### ISSUE TITLE
Add git to LangGraph App Docker Image

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langgraph-studio#73]
Problem:
Pip packages which use Git fail to install complaining Git is not installed.
Workaround:
{
  "dockerfile_lines": [
    "RUN apt-get update && apt-get install -y git",
However, this incurs a startup cost to build each start of the app

**Comment by amsmith87** [comment]
Thanks for the workaround! I'm having this issue as well -- where can I find the file that you edited to make these changes?

**Comment by Glavin001** [comment]
@amsmith87 edit your `langgraph.json` file to add `dockerfile_lines`.

- Docs for `langgraph.json`: https://langchain-ai.github.io/langgraph/cloud/reference/cli/#configuration-file
- Tutorial for setting up a repo: https://langchain-ai.github.io/langgraph/cloud/quick_start/#set-up-local-files
- Example repo: https://github.com/hwchase17/langgraph-engineer/blob/main/langgraph.json#L3

**Comment by dqbd** [comment]
Should be now included within the image now by defaylt!
