### ISSUE TITLE
Mount a folder to the docker image

### ISSUE THREAD

**Issue by lfnovo** [langchain-ai/langgraph-studio#75]
Hello, is it possible to mount a local volume to the docker app that is built by Langgraph?

**Comment by hwchase17** [comment]
all folders that are in the directory you open should be mounted, are you seeing otherwise?

**Comment by danmas0n** [comment]
I am also kind of stuck on this -- basically my agent graph needs to operate on a codebase so I need both my tool and the codebase itself to be in the container, and be able to run test suites on both, that sort of thing.  I added both codebases as dependencies as a way to force them both to load but not ideal.  I shelled into the Docker container and confirmed nothing was mounted externally.  

I could do most of what I need to do if the directory that contains langgraph.json was mounted to the container, but ideally I also want the ability for agents to "npm run test", either inside or outside the container.  I don't think you can pull this off with the two mechanisms you expose right now (Dockerfile or docker-compose.yml) but if you have any relevant samples that would be awesome...

**Comment by dqbd** [comment]
Hello! You can use the `docker_compose_file` entry with the following contents to mount folders to the API image

`langgraph.json`
```json
{ "docker_compose_file": "./docker-compose.extend.yml" }
```

`docker-compose.extend.yml`
```yaml
services:
  langgraph-api:
    volumes:
      - ./static:/raw/static
```
