### ISSUE TITLE
Graph state does not reset when starting a new thread in LangGraph Studio

### ISSUE THREAD

**Issue by hardiknahata** [langchain-ai/langgraph-studio#77]
- Initial Graph State:
```
{
"documents": []
}
```

- Graph State after Thread-1 executes:
```
{
"documents": ["sample doc from output of thread-1"]
}
```

- Started new thread

- Graph State after Thread-2 executes:
```
{
"documents": ["sample doc from output of thread-2", "sample doc from output of thread-1"]
}
```

---
I want the graph state to be reset when i start a new thread. Shouldn't the default behavior be to reset the state when a new thread starts? If not, how can I achieve this? I can think one way is to reset my state via code after every run, but that could cause issues in long run i feel. Any help would be appreciated.

LangGraph version `0.2.3`

**Comment by hwchase17** [comment]
can you share a video of what is happening? and more information about your graph

**Comment by hardiknahata** [comment]
Hi @hwchase17 , it works now, I think had some issue in implementation. Thanks
