### ISSUE TITLE
ConnectionError [Errno111] - when invoking locally running Ollama model

### ISSUE THREAD

**Issue by SampsonM** [langchain-ai/langgraph-studio#78]
<img width="317" alt="image" src="https://github.com/user-attachments/assets/88a8c339-4f5c-4ee8-a647-854ab94f186f">

<img width="336" alt="image" src="https://github.com/user-attachments/assets/572c039d-602a-439e-a87f-231012896079">

When trying to use a locally running Ollama model I get the above error when trying to invoke the model.

Ollama is running and I can send messages from within the terminal but not from LangGraph Studio

Using the langchain_ollama package to invoke the model - https://api.python.langchain.com/en/latest/llms/langchain_ollama.llms.OllamaLLM.html

The only error I'm seeing in the logs is below.

Any ideas?

```
Retrying task buyer after 0.15 seconds (attempt 1) after ConnectError [Errno 111] Connection refused
```

**Comment by dqbd** [comment]
Hello! LangGraph itseif is running within a Docker container. Thus, in order to reach the Ollama server running locally on host, you need to use the `host.docker.internal` hostname instead
