### ISSUE TITLE
State has unexpected defaults

### ISSUE THREAD

**Issue by ewalker11** [langchain-ai/langgraph-studio#79]
# Issue

I am seeing some unexpected behavior with the way that LangGraph Studio integrates with LangGraph state where State is defined as a pydantic BaseMode with defaults

## State with non-optional values with defaults

```python

from typing import Any, Dict, List
from pydantic import BaseModel
from langgraph.graph import StateGraph, START, END


class State(BaseModel):
    string_default: str = ""
    int_default: int = 0
    float_default: float = 0
    dict_default: Dict[str, Any] = {}
    list_default: List[str] = []


def node(state: State):
    return {
        'string_default': state.string_default,
        'int_default': state.int_default,
        'float_default': state.float_default,
        'dict_default': state.dict_default,
        'list_default': state.list_default,
    }


graph_builder = StateGraph(State)
graph_builder.add_node("default", node)
graph_builder.add_edge(START, "default")
graph_builder.add_edge("default", END)

graph = graph_builder.compile()
```

### Expected Behavior
I expect:
1. Invoking the graph via SDK and LangGraph Studio with None state should progress normally, with the State taking on the default values for each field
2. Ditto for submitting state as an empty dict
3. Invoking the graph with any of the State fields explicitly set should work, with the unspecified fields taking on their default fields

#### SDK
1. ❌ Error `{"detail":"Received no input for __start__"}`
2. ❌ Error `{"detail":"Must write to at least one of ['string_default', 'int_default', 'float_default', 'dict_default', 'list_default']"}`
3. ❌ If submitting state as:

```json
{
  "string_default": "foobar"
}
```

Error: `{"detail":"4 validation errors for State\nint_default\n  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType...`

When you instantiate State manually like so, there are no errors:

```python
>>> State(string_default="foobar")
State(string_default='foobar', int_default=0, float_default=0, dict_default={}, list_default=[])
```

#### LangGraph Studio
1. ❌ `string_default` is set to "None Provided". All other fields have correct defaults
<img width="306" alt="image" src="https://github.com/user-attachments/assets/62769612-be91-4686-9559-9b474d78f96b">
2. No differentiation between submitting None/empty dict input on Studio
3. ❌ Setting the string_value input to "foobar" results in the following error (which is the same as the SDK behavior)

<img width="336" alt="image" src="https://github.com/user-attachments/assets/e1ad2957-7a4c-4c75-a3c7-e501d816d3ee">

This is especially confusing since the UI says that all state fields are "Optional"

<img width="445" alt="image" src="https://github.com/user-attachments/assets/78c3c91f-9f2f-4dba-ab59-f4400636a974">

## State with optional values with defaults. 

Same graph as above with different state:

```python
class State(BaseModel):
    string_default: Optional[str] = None
    int_default: Optional[int] = None
    float_default: Optional[float] = None
    dict_default: Optional[Dict[str, Any]] = None
    list_default: Optional[List[str]] = None
```

### Expected Behavior
I expect:
1. Invoking the graph via SDK and LangGraph Studio with None state should progress normally, with the State taking on `None` values for all fields
2. Ditto for submitting state as an empty dict
3. Invoking the graph with any of the State fields explicitly set should work, with the unspecified fields taking on `None` values

#### SDK
1. ❌  Error `{"detail":"Received no input for __start__"}`
2. ❌ Error `{"detail":"Must write to at least one of ['string_default', 'int_default', 'float_default', 'dict_default', 'list_default']"}`
3. ✅ As expected. If submitting state as:

```json
{
  "string_default": "foobar"
}
```
Completes successfully with result:

```python
{'string_default': 'foobar',
 'int_default': None,
 'float_default': None,
 'dict_default': None,
 'list_default': None}
```

#### LangGraph Studio
1. ❌ Submitting with no state values set results in LangGraph studio filling non-null defaults for the State fields. Leading to this output:

<img width="305" alt="image" src="https://github.com/user-attachments/assets/da91da28-c2c2-4c9b-90f3-d3714c725baf">

2. No differentiation between submitting None/empty dict input on Studio
3. ✅ As expected. Runs with the following result:

<img width="277" alt="image" src="https://github.com/user-attachments/assets/6a670ee2-9e2e-4fcb-bbc1-cf6c73a2753b">

**Comment by hwchase17** [comment]
Thanks for flagging! In general, we see more usage of TypedDict and so have tested/optimized less for Pydantic (for studio in particular). So these are helpful issues!

> Error {"detail":"Received no input for __start__"}

We currently require input to the graph of some form - so this is as currently constructed an expected error. Will look into relaxing this constraint

>  Error {"detail":"Must write to at least one of ['string_default', 'int_default', 'float_default', 'dict_default', 'list_default']"}

Same here, we require that the input must write to one of the existing channels. Again, we can look into relaxing this constraint but this is currently an expected exception that this throws

> {"detail":"4 validation errors for State\nint_default\n  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType

This is less intuitive/expected - we assign a value of None to channels without any input, and this None value is getting passed in. Will look into whether it makes sense to filter these out or whether we cant really do that

**Comment by dqbd** [comment]
Will update Studio to not show "Not provided" when an empty string is present, rather to show "Empty string" instead.
