### ISSUE TITLE
Add support for self-signed certificates and loading certificates from system store

### ISSUE THREAD

**Issue by dqbd** [langchain-ai/langgraph-studio#81]
Current workaround is to add the certificate to `/usr/local/lib/python3.11/site-packages/certifi`

**Comment by Barneyjm** [comment]
langgraph.json
```json
{
  "python_version": "3.11",
  "dockerfile_lines": [
    "COPY my_self_signed_cert.crt /etc/ssl/certs/",
    "RUN cat /etc/ssl/certs/my_self_signed_cert.crt >> /usr/local/lib/python3.11/site-packages/certifi/cacert.pem"
  ],
  "dependencies": [
    "."
  ],
  "graphs": {
    "agent": "./agent.py:graph"
  },
  "env": []
}
```

**Comment by dcalsky** [comment]
> langgraph.json
> 
> ```json
> {
>   "python_version": "3.11",
>   "dockerfile_lines": [
>     "COPY my_self_signed_cert.crt /etc/ssl/certs/",
>     "RUN cat /etc/ssl/certs/my_self_signed_cert.crt >> /usr/local/lib/python3.11/site-packages/certifi/cacert.pem"
>   ],
>   "dependencies": [
>     "."
>   ],
>   "graphs": {
>     "agent": "./agent.py:graph"
>   },
>   "env": []
> }
> ```

It works for me. Thank you!

**Comment by dqbd** [comment]
Hello! We've released a new version of LangGraph CLI, which avoids using Docker, thus no workarounds are needed to support custom certificates!

See https://langchain-ai.github.io/langgraph/how-tos/local-studio/ for more details!
