### ISSUE TITLE
Multiple images created for the same project

### ISSUE THREAD

**Issue by henryf3** [langchain-ai/langgraph-studio#82]
I am running LangGraph Studio v0.0.12 and Docker Desktop 4.33.0, but everytime I run my project it creates a new docker image, causing my docker disk space to be filled too quickly. Is it an intended behaviour? or am I missing some configuration to not create new docker images every time?
![image](https://github.com/user-attachments/assets/6a2522be-d503-48f1-8768-84a2134c2ece)

**Comment by dqbd** [comment]
Hello @henryf3! This will be addressed with the next update. In the meantime, you can use `docker system prune` to get rid of dangling images

**Comment by dqbd** [comment]
Should be resolved in 0.0.13!
