### ISSUE TITLE
Could not resolve authentication method. Expected either api_key or auth_token to be set

### ISSUE THREAD

**Issue by AlSaltAlBahri** [langchain-ai/langgraph-studio#9]
Hello, 

I am trying to get the langgraph-example up and running but I'm getting this issue 

<img width="1183" alt="Screenshot 2024-08-02 at 1 52 30 AM" src="https://github.com/user-attachments/assets/aeebf462-ef7f-4378-9d5e-043caa97692e">

**Comment by dqbd** [comment]
Hello @AlSaltAlBahri! Would it be possible to share the logs? 

Also: is it possible that you've set an empty key for OPENAI_API_KEY / ANTHROPIC_API_KEY or TAVILY_API_KEY?

**Comment by smoms** [comment]
I get same error
