### ISSUE TITLE
Langgraph Studio showing AttributeError: 'NoneType' object has no attribute 'pending_writes'

### ISSUE THREAD

**Issue by henryf3** [langchain-ai/langgraph-studio#91]
Hi, I am using Langraph Studio 0.012, it was working perfectly until yesterday, now it shows this error:
![image](https://github.com/user-attachments/assets/41c0dfa5-df4c-4e05-b030-95e0c037e19d)

I think is due to the update to the langraph library, in this commit they added the method pending_writes():
https://github.com/langchain-ai/langgraph/commit/e916cab08ff2e1a044553e59939b05c7b93f274d

Now, I tried to fix my version to 0.2.4 (the one that works running python3 locally), but there is a dependency conflict saying:

![image](https://github.com/user-attachments/assets/0f2c535a-713e-4274-8de7-9fa033c5c407)

But my requirements.txt file just has these lines regarding langgraph-langchain libraries:

```
langgraph<=0.2.3
langchain-anthropic
langchain
langchain-openai
```

**Comment by dqbd** [comment]
Hello @henryf3! I think you might need to update your `requirements.txt` to `langgraph<=0.2.7`?

**Comment by henryf3** [comment]
@dqbd I need to use 0.2.4 or lower, do you restrict internally the langgraph version to be >= 0.2.7?
Changing it to langgraph<=0.2.7 stills have the same problem:
![image](https://github.com/user-attachments/assets/4ff257ae-04c6-4b62-86c8-f04102d7f485)

**Comment by nfcampos** [comment]
Hi @henryf3 we published a new version this morning that fixes this issue. We do not support using old langgraph versions with studio. Any particular reason you want to use 0.2.4?
