### ISSUE TITLE
[Feature Request] Nested graph diagram

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langgraph-studio#92]
Hi, I am using subgraphs with two levels of nesting. The Studio UI's architecture only shows the top-level graph, and none of the subgraph nodes. I'd like to submit this as a feature request if it's not already available.

**Comment by gutmmm** [comment]
+1

**Comment by arthberman** [comment]
+1

**Comment by yesid-lopez** [comment]
+1

**Comment by ekolasky** [comment]
+1

**Comment by dqbd** [comment]
Released in 0.0.28!
