### ISSUE TITLE
Feature request: Support for calling local endpoints

### ISSUE THREAD

**Issue by amsmith87** [langchain-ai/langgraph-studio#95]
Any functions that call to localhost endpoints return 404 (likely due to nested containers). I am able to call these using LangGraph locally, and by running curl within my project's image (using "http://host.docker.internal:8000/") -- but this does not work within LangGraph Studio.

**Comment by gutmmm** [comment]
It works in my LangGraph Studio project. I'm calling my local services with `http://host.docker.internal:port` just fine.

**Comment by amsmith87** [comment]
Thanks for verifying! Turned out to be an unfortunately timed intermittent issue with my endpoint.
