### ISSUE TITLE
[Feature Suggestion] Bring your own environment.

### ISSUE THREAD

**Issue by jcoombes** [langchain-ai/langgraph-studio#96]
I have set up my python following 
https://alysivji.github.io/setting-up-pyenv-virtualenvwrapper.html

failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1

Why can't I just use my own environment, especially if I want to switch to `uv pip` in the future.

**Comment by dqbd** [comment]
Hello! We use Docker to build the API image of the graph, which can be then deployed to LangGraph Cloud, thus it is required to describe the expected environment via `requirements.txt` and/or `pyproject.toml`, thus bringing own environment is currently not planned.
