### ISSUE TITLE
0.0.15 passes in a Fragment object instead of a RunnableConfig

### ISSUE THREAD

**Issue by amsmith87** [langchain-ai/langgraph-studio#97]
In the previous version, I was using a function as an entry point to building my graph. This function takes in one parameter, a RunnableConfig (from [LangGraph CLI docs](https://langchain-ai.github.io/langgraph/cloud/reference/cli/)).

In 0.0.15, this is now a `langgraph_api.shared.serde.Fragment`, which throws an error when running dict functions to access: `AttributeError: 'Fragment' object has no attribute 'get'"}`. While I don't expect any contents when running LangGraph Studio at the moment, I do re-use this function when running from the command line where the RunnableConfig contents are not empty. If this is expected, what is the intended way to load data from this object?

**Comment by nfcampos** [comment]
Ah my apologies, this is fixed in the next release, should be published in 15mins
